services:
  laravel:
    ports:
      - "${APP_PORT:-8000}:80"
      - "5173:5173"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./app:/var/www/html/app
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./docker/php-dev.ini:/usr/local/etc/php/conf.d/zzz-dev.ini
